# Generated by Django 4.2.11 on 2024-04-07 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wilayah', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provinsi',
            options={'ordering': ['id']},
        ),
        migrations.CreateModel(
            name='Kabupaten_Kota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kabupaten_kota', models.CharField()),
                ('provinsi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wilayah.provinsi')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
