# Generated by Django 4.2.11 on 2024-04-07 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wilayah', '0002_alter_provinsi_options_kabupaten_kota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kabupaten_kota',
            name='kabupaten_kota',
            field=models.CharField(max_length=100),
        ),
    ]
