# Generated by Django 4.2.11 on 2024-04-07 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wilayah', '0003_alter_kabupaten_kota_kabupaten_kota'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kabupaten_kota',
            options={'ordering': ['provinsi_id']},
        ),
    ]
