# Generated by Django 4.2.11 on 2024-04-08 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wilayah', '0004_alter_kabupaten_kota_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='kabupaten_kota',
            name='predikat',
            field=models.CharField(blank=True, choices=[('kabupaten', 'Kabupaten'), ('kota', 'Kota')], max_length=20, null=True),
        ),
    ]
