# Generated by Django 4.2.11 on 2024-04-08 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wilayah', '0006_alter_kabupaten_kota_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kabupaten_kota',
            name='predikat',
            field=models.CharField(blank=True, choices=[('Kabupaten', 'Kabupaten'), ('Kota', 'Kota')], max_length=20, null=True),
        ),
    ]
