# Generated by Django 4.2.11 on 2024-04-08 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wilayah', '0008_alter_kabupaten_kota_predikat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kabupaten_kota',
            name='predikat',
            field=models.CharField(blank=True, choices=[('Kabupaten', 'Kabupaten'), ('Kota', 'Kota'), ('DKI', 'Daerah Khusus Ibukota'), ('DI', 'Daerah Istimewa'), ('Kota Adm.', 'Kota Administrasi'), ('Kab. Adm.', 'Kabupaten Administrasi')], max_length=20, null=True),
        ),
    ]
