# Generated by Django 4.1.11 on 2023-09-11 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Penerbit_Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, max_length=255)),
                ('penerbit', models.CharField(max_length=100)),
                ('instansi', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['penerbit'],
            },
        ),
        migrations.CreateModel(
            name='Penulis_Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, max_length=255)),
                ('nama_penulis', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nama_penulis'],
            },
        ),
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, max_length=255)),
                ('judul_buku', models.CharField(max_length=255)),
                ('tahun', models.IntegerField()),
                ('deskripsi', models.TextField()),
                ('penerbit', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='produk.penerbit_buku')),
                ('penulis', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='produk.penulis_buku')),
            ],
            options={
                'ordering': ['judul_buku'],
            },
        ),
    ]
