# Generated by Django 4.1.11 on 2023-10-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0002_buku_sampul_buku_buku_thumbnail_sampul'),
    ]

    operations = [
        migrations.AddField(
            model_name='penulis_buku',
            name='nama',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='penulis_buku',
            name='tentang_penulis',
            field=models.TextField(blank=True),
        ),
    ]
