# Generated by Django 4.1.11 on 2023-10-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0003_penulis_buku_nama_penulis_buku_tentang_penulis'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='harga',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
