# Generated by Django 4.1.11 on 2024-02-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0004_buku_harga'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='stok_barang',
            field=models.IntegerField(default=0),
        ),
    ]
