# Generated by Django 4.1.11 on 2024-02-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0005_buku_stok_barang'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stationery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, max_length=255)),
                ('nama_produk', models.CharField(max_length=255)),
                ('gambar_produk', models.CharField(blank=True, max_length=255)),
                ('stok_barang', models.IntegerField(default=0)),
                ('harga', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['nama_produk'],
            },
        ),
    ]
