# Generated by Django 4.1.11 on 2024-03-01 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0006_stationery'),
    ]

    operations = [
        migrations.AddField(
            model_name='penerbit_buku',
            name='tentang_penerbit',
            field=models.TextField(default=''),
        ),
    ]
