# Generated by Django 4.1.11 on 2024-03-01 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0007_penerbit_buku_tentang_penerbit'),
    ]

    operations = [
        migrations.AddField(
            model_name='penerbit_buku',
            name='logo_penerbit',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='buku',
            name='harga',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='penerbit_buku',
            name='tentang_penerbit',
            field=models.TextField(blank=True, default=''),
        ),
    ]
