# Generated by Django 4.1.11 on 2024-03-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0008_penerbit_buku_logo_penerbit_alter_buku_harga_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penerbit_buku',
            name='logo_penerbit',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='penerbit_buku',
            name='tentang_penerbit',
            field=models.TextField(blank=True),
        ),
    ]
