# Generated by Django 4.1.11 on 2024-03-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0009_alter_penerbit_buku_logo_penerbit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='penulis_buku',
            name='foto_profil',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
