# Generated by Django 4.1.11 on 2024-03-05 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0010_penulis_buku_foto_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penulis_buku',
            name='foto_profil',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
