# Generated by Django 4.1.11 on 2024-03-16 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0011_alter_penulis_buku_foto_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='isbn',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='buku',
            name='penerbit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produk.penerbit_buku'),
        ),
        migrations.AlterField(
            model_name='buku',
            name='penulis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produk.penulis_buku'),
        ),
    ]
