# Generated by Django 4.1.11 on 2024-03-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0012_buku_isbn_alter_buku_penerbit_alter_buku_penulis'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='kategori',
            field=models.CharField(default='buku', editable=False, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='penerbit_buku',
            name='kategori',
            field=models.CharField(default='penerbit', editable=False, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='penulis_buku',
            name='kategori',
            field=models.CharField(default='penulis', editable=False, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stationery',
            name='kategori',
            field=models.CharField(default='stationery', editable=False, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buku',
            name='judul_buku',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='penerbit_buku',
            name='penerbit',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='penulis_buku',
            name='nama_penulis',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
