# Generated by Django 4.1.11 on 2024-03-20 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0013_buku_kategori_penerbit_buku_kategori_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='kategori',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='penerbit_buku',
            name='kategori',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='penulis_buku',
            name='kategori',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stationery',
            name='kategori',
            field=models.CharField(max_length=100),
        ),
    ]
