# Generated by Django 4.1.11 on 2024-03-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0014_alter_buku_kategori_alter_penerbit_buku_kategori_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='kategori',
            field=models.CharField(choices=[('penulis', 'Penulis'), ('penerbit', 'Penerbit'), ('buku', 'Buku'), ('stationery', 'Stationery')], max_length=50),
        ),
        migrations.AlterField(
            model_name='penerbit_buku',
            name='kategori',
            field=models.CharField(choices=[('penulis', 'Penulis'), ('penerbit', 'Penerbit'), ('buku', 'Buku'), ('stationery', 'Stationery')], max_length=50),
        ),
        migrations.AlterField(
            model_name='penulis_buku',
            name='kategori',
            field=models.CharField(choices=[('penulis', 'Penulis'), ('penerbit', 'Penerbit'), ('buku', 'Buku'), ('stationery', 'Stationery')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stationery',
            name='kategori',
            field=models.CharField(choices=[('penulis', 'Penulis'), ('penerbit', 'Penerbit'), ('buku', 'Buku'), ('stationery', 'Stationery')], max_length=50),
        ),
    ]
