# Generated by Django 4.2.11 on 2024-04-05 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0015_alter_buku_kategori_alter_penerbit_buku_kategori_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='berat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='buku',
            name='harga_diskon',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='buku',
            name='is_discount',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buku',
            name='jumlah_halaman',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='buku',
            name='lebar',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='buku',
            name='panjang',
            field=models.FloatField(default=0.0),
        ),
    ]
