# Generated by Django 4.2.11 on 2024-04-05 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0016_buku_berat_buku_harga_diskon_buku_is_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationery',
            name='harga_diskon',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stationery',
            name='is_discount',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
