# Generated by Django 4.2.11 on 2024-04-05 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0017_stationery_harga_diskon_stationery_is_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='is_discount',
            field=models.BooleanField(default=False),
        ),
    ]
