# Generated by Django 4.2.11 on 2024-04-05 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0018_alter_buku_is_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='is_discount',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
