# Generated by Django 4.2.11 on 2024-04-05 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0019_alter_buku_is_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stationery',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buku',
            name='is_discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stationery',
            name='is_discount',
            field=models.BooleanField(default=False),
        ),
    ]
