# Generated by Django 4.2.11 on 2024-05-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0020_buku_discount_stationery_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='kategori',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='penerbit_buku',
            name='kategori',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='penulis_buku',
            name='kategori',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='stationery',
            name='kategori',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
    ]
